export const rightsStatuses = [
  'public-link-reference-only',
  'licensed-for-reuse',
  'public-domain',
  'cc-licensed',
  'unknown-link-only',
]

export const previewModes = ['original_pip_interpretation', 'licensed_original_preview']

export const sourceRecords = [
  {
    sourceTitle: 'Salesforce Investor Day 2022', sourceOrganization: 'Salesforce',
    sourceUrl: 'https://investor.salesforce.com/events-and-presentations/events/event-details/2022/Salesforce-Investor-Day-2022/default.aspx',
    sourceType: 'investor-presentation', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Публичная investor-презентация показывает, как сравнение вариантов подчиняется одному коммерческому выбору и ясной рекомендации.',
    adaptationPrinciple: 'Сравнительная логика с выделенным рекомендуемым пакетом и решающими критериями.',
    originalDifference: 'PIP использует другие тарифные модели, критерии и визуальную систему; логотипы и фирменная графика Salesforce не воспроизводятся.',
  },
  {
    sourceTitle: 'HubSpot Investor Presentation', sourceOrganization: 'HubSpot',
    sourceUrl: 'https://ir.hubspot.com/static-files/7f47c817-fa7f-4462-a4f3-43515fd0c863',
    sourceType: 'investor-presentation', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Источник полезен сочетанием крупной итоговой метрики, драйверов роста и компактного доказательства экономики решения.',
    adaptationPrinciple: 'Одна экономическая история: инвестиция, эффект, окупаемость и чувствительность.',
    originalDifference: 'Все показатели и подписи синтетические; композиция и цветовая система разработаны PIP без брендовых элементов HubSpot.',
  },
  {
    sourceTitle: 'Asana Investor Day', sourceOrganization: 'Asana',
    sourceUrl: 'https://investors.asana.com/events/event-details/asana-investor-day-2023',
    sourceType: 'investor-presentation', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Публичный deck демонстрирует последовательную value story: проблема, изменение способа работы и измеримый результат.',
    adaptationPrinciple: 'Трёхактная аргументация с контрастом текущего состояния и будущего эффекта.',
    originalDifference: 'Сюжет, данные и иллюстративные формы созданы заново; PIP не копирует продуктовый интерфейс или фирменную графику Asana.',
  },
  {
    sourceTitle: 'Create + prepare slides', sourceOrganization: 'TED',
    sourceUrl: 'https://www.ted.com/participate/organize-a-local-tedx-event/tedx-organizer-guide/speakers-program/prepare-your-speaker/create-prepare-slides',
    sourceType: 'presentation-guidance', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Рекомендации TED помогают строить слайд вокруг одной понятной идеи и поддерживать речь визуальным ритмом.',
    adaptationPrinciple: 'Один сильный тезис, эмоциональная пауза и минимальное количество поддерживающего текста.',
    originalDifference: 'Это самостоятельная редакционная композиция PIP без знака TED, цитат и копирования конкретного кадра выступления.',
  },
  {
    sourceTitle: 'The secret structure of great talks', sourceOrganization: 'TED / Nancy Duarte',
    sourceUrl: 'https://www.ted.com/speakers/nancy_duarte',
    sourceType: 'public-talk', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Выступление раскрывает драматургию контраста между текущим положением и желаемым будущим.',
    adaptationPrinciple: 'Keynote-композиция с чередованием «сейчас» и «может быть» и ясной кульминацией.',
    originalDifference: 'PIP применяет принцип контраста к новой теме и собственной визуальной метафоре, без кадров и текста оригинального выступления.',
  },
  {
    sourceTitle: 'The art of persuasive storytelling', sourceOrganization: 'TED / Kelly D. Parker',
    sourceUrl: 'https://www.ted.com/talks/kelly_d_parker_the_art_of_persuasive_storytelling',
    sourceType: 'public-talk', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Публичное выступление показывает, как конкретные моменты опыта складываются в убедительную историю.',
    adaptationPrinciple: 'Сюжет из трёх сцен с нарастающим эмоциональным и смысловым весом.',
    originalDifference: 'История, подписи, числовые факты и графическое решение полностью оригинальны и не воспроизводят материалы TED.',
  },
  {
    sourceTitle: 'Guidance on developing business cases', sourceOrganization: 'HM Treasury',
    sourceUrl: 'https://www.gov.uk/government/publications/guidance-on-developing-business-cases',
    sourceType: 'government-guidance', rightsStatus: 'licensed-for-reuse', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Five Case Model задаёт проверяемую структуру обоснования проекта: стратегический эффект, варианты, реализуемость и риски.',
    adaptationPrinciple: 'Взвешенная матрица решения и видимая связь критериев с рекомендацией.',
    originalDifference: 'Матрица, веса, оценки и оформление созданы PIP; официальный текст и государственная айдентика не копируются.',
  },
  {
    sourceTitle: 'Strategic Perspectives on the Future of Systems Engineering at NASA', sourceOrganization: 'NASA',
    sourceUrl: 'https://ntrs.nasa.gov/citations/20205002911',
    sourceType: 'technical-guidance', rightsStatus: 'public-domain', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Технический материал полезен точной декомпозицией причин, интерфейсов и проверочных действий.',
    adaptationPrinciple: 'Причинная цепочка от симптома к корневой причине, влиянию и контролю исправления.',
    originalDifference: 'PIP создаёт новый интеграционный кейс и собственную инфографику; схемы NASA не вставляются и не перерисовываются.',
  },
  {
    sourceTitle: 'Agile Assessment Guide', sourceOrganization: 'U.S. Government Accountability Office',
    sourceUrl: 'https://www.gao.gov/products/gao-24-105506',
    sourceType: 'government-guidance', rightsStatus: 'public-domain', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Руководство GAO показывает, как связать этапы реализации с доказательствами готовности и контрольными точками.',
    adaptationPrinciple: 'Roadmap с потоками работ, сроками, владельцами, статусами и exit-критериями.',
    originalDifference: 'Сроки, проектные потоки и данные вымышлены для PIP; визуальный язык GAO не воспроизводится.',
  },
  {
    sourceTitle: 'DACI decision-making framework', sourceOrganization: 'Atlassian',
    sourceUrl: 'https://www.atlassian.com/team-playbook/plays/daci',
    sourceType: 'team-playbook', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'DACI делает решение операционным: видны роли, владелец, участники, входные данные и момент фиксации.',
    adaptationPrinciple: 'Рабочий процесс совещания, где у каждого шага есть результат, роль и срок.',
    originalDifference: 'PIP использует собственный процесс из четырёх стадий и нейтральную графику без копирования шаблона Atlassian.',
  },
  {
    sourceTitle: 'Project Poster play', sourceOrganization: 'Atlassian',
    sourceUrl: 'https://www.atlassian.com/team-playbook/plays/project-poster?tab=instructions',
    sourceType: 'team-playbook', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Project Poster объединяет факты, вопросы и следующие решения на одной рабочей поверхности.',
    adaptationPrinciple: 'Meeting-dashboard с разделением здоровья программы, блокеров и решений недели.',
    originalDifference: 'Метрики, статусы, структура блоков и визуальное оформление разработаны PIP; исходный шаблон не копируется.',
  },
  {
    sourceTitle: 'Making decisions playbook examples', sourceOrganization: 'Atlassian',
    sourceUrl: 'https://www.atlassian.com/team-playbook/examples/making-decisions',
    sourceType: 'team-playbook', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Примеры полезны для формата, в котором спорные требования, владельцы и решения видны всей команде.',
    adaptationPrinciple: 'Плотная decision-table с явными статусами, разногласиями и следующими действиями.',
    originalDifference: 'Требования и решения синтетические, таблица спроектирована заново и не использует брендовые компоненты Atlassian.',
  },
  {
    sourceTitle: 'Annual Report 2024', sourceOrganization: 'World Bank',
    sourceUrl: 'https://www.worldbank.org/en/about/annual-report-2024',
    sourceType: 'annual-report', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Годовой отчёт демонстрирует управленческий ритм: ключевые показатели, динамика и короткий вывод о результате периода.',
    adaptationPrinciple: 'KPI-экран с ограниченным набором метрик, временным рядом и объяснением драйвера.',
    originalDifference: 'Показатели относятся к вымышленной компании; PIP использует собственную сетку, палитру и редакционный текст.',
  },
  {
    sourceTitle: 'UNDP Annual Report 2024', sourceOrganization: 'United Nations Development Programme',
    sourceUrl: 'https://www.undp.org/publications/undp-annual-report-2024',
    sourceType: 'annual-report', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Отчёт показывает, как на одном развороте объединить план, факт, прогноз и объяснение отклонений.',
    adaptationPrinciple: 'Финансовый dashboard с иерархией: итог, драйверы, forecast и управленческий вывод.',
    originalDifference: 'Все финансовые данные и графики сгенерированы для PIP; символика и инфографика UNDP не используются.',
  },
  {
    sourceTitle: 'UNICEF Annual Report 2024', sourceOrganization: 'UNICEF',
    sourceUrl: 'https://www.unicef.org/reports/unicef-annual-report/2024',
    sourceType: 'annual-report', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Источник полезен связью измеримого отклонения с причинами, владельцами и корректирующими действиями.',
    adaptationPrinciple: 'Pareto причин рядом с таблицей влияния, срока и ответственного.',
    originalDifference: 'SLA-кейс и все значения оригинальны; PIP не использует фотографии, логотипы или фирменные элементы UNICEF.',
  },
  {
    sourceTitle: 'Pathways to Success', sourceOrganization: 'The Open University / OpenLearn',
    sourceUrl: 'https://www.open.edu/openlearn/pathway',
    sourceType: 'learning-resource', rightsStatus: 'cc-licensed', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Учебный путь показывает понятную прогрессию от знакомства с темой к самостоятельному применению.',
    adaptationPrinciple: 'Пошаговый учебный маршрут с действием, инструментом и критерием освоения.',
    originalDifference: 'Пять этапов, задания и графический стиль созданы PIP; материалы курса не воспроизводятся.',
  },
  {
    sourceTitle: 'Visual tools for learning', sourceOrganization: 'The Open University / OpenLearn',
    sourceUrl: 'https://www.open.edu/openlearn/education-development/extending-and-developing-your-thinking-skills/content-section-7.4',
    sourceType: 'learning-resource', rightsStatus: 'cc-licensed', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Материал показывает, как дорожная карта обучения связывает темы, практику, проверку и результат.',
    adaptationPrinciple: 'Календарный learning-path с контрольными точками и наблюдаемыми результатами.',
    originalDifference: 'Программа, длительности и визуальная система полностью новые; исходные учебные иллюстрации не копируются.',
  },
  {
    sourceTitle: 'Open Pathways', sourceOrganization: 'The Open University / OpenLearn',
    sourceUrl: 'https://www.open.edu/openlearn/course/view.php?id=12020',
    sourceType: 'learning-resource', rightsStatus: 'cc-licensed', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Курс полезен балансом концептуального объяснения, примера и проверочного задания.',
    adaptationPrinciple: 'Одна концепция раскрывается через тезис, пример и перенос в рабочую ситуацию.',
    originalDifference: 'Тема, кейс, текст и визуальная метафора придуманы для PIP и не повторяют страницы OpenLearn.',
  },
  {
    sourceTitle: 'UNDP Strategic Plan 2022–2025', sourceOrganization: 'United Nations Development Programme',
    sourceUrl: 'https://www.undp.org/publications/undp-strategic-plan-2022-2025',
    sourceType: 'strategy-report', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Стратегический план связывает долгосрочное направление, портфель инициатив и измеримые результаты.',
    adaptationPrinciple: 'Roadmap с горизонтами, стратегическими ставками, владельцами и метриками успеха.',
    originalDifference: 'Стратегические направления и показатели принадлежат вымышленной организации; визуальный код UNDP не копируется.',
  },
  {
    sourceTitle: 'NASA Strategic Plan', sourceOrganization: 'NASA',
    sourceUrl: 'https://www.nasa.gov/ocfo/strategic-plan/',
    sourceType: 'strategy-report', rightsStatus: 'public-domain', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Публичный стратегический план показывает иерархию от миссии к целям, инициативам и показателям.',
    adaptationPrinciple: 'Карта стратегических опор с причинной связью между инициативами и итоговым эффектом.',
    originalDifference: 'PIP использует коммерческий контекст, новые формулировки и собственные формы; материалы NASA не встраиваются.',
  },
  {
    sourceTitle: 'National Digital Decade strategic roadmaps', sourceOrganization: 'European Commission',
    sourceUrl: 'https://digital-strategy.ec.europa.eu/en/policies/national-strategic-roadmaps',
    sourceType: 'strategy-roadmap', rightsStatus: 'public-link-reference-only', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Roadmaps полезны сочетанием целевых состояний, этапов, ответственности и измеримых контрольных точек.',
    adaptationPrinciple: 'Сценарное сравнение трёх стратегических путей по эффекту, риску и скорости.',
    originalDifference: 'Сценарии и расчёты оригинальны; PIP не копирует карты, символику ЕС или содержание национальных планов.',
  },
  {
    sourceTitle: 'Supporting documents for Budget 2025', sourceOrganization: 'HM Treasury',
    sourceUrl: 'https://www.gov.uk/government/publications/supporting-documents-for-budget-2025',
    sourceType: 'budget-report', rightsStatus: 'licensed-for-reuse', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Бюджетные документы показывают дисциплину раскрытия базы, изменений, итогов и допущений.',
    adaptationPrinciple: 'Бюджетная таблица с арифметически согласованными статьями и видимым итогом инвестиции.',
    originalDifference: 'Статьи, суммы и назначение бюджета придуманы для PIP; государственные таблицы и оформление не копируются.',
  },
  {
    sourceTitle: 'Cost Estimate — H.R. 1908', sourceOrganization: 'Congressional Budget Office',
    sourceUrl: 'https://www.cbo.gov/publication/61419',
    sourceType: 'cost-estimate', rightsStatus: 'public-domain', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Оценка CBO полезна прозрачным разделением затрат, выгод, сроков и чувствительности к допущениям.',
    adaptationPrinciple: 'Cost/benefit-сравнение с итогом, накопленным эффектом и точкой окупаемости.',
    originalDifference: 'Финансовая модель и категории новые; PIP не переносит числа, таблицы или официальный стиль CBO.',
  },
  {
    sourceTitle: 'Local authority revenue expenditure and financing 2025–26', sourceOrganization: 'UK Ministry of Housing, Communities and Local Government',
    sourceUrl: 'https://www.gov.uk/government/statistics/local-authority-revenue-expenditure-and-financing-england-2025-to-2026-budget/local-authority-revenue-expenditure-and-financing-2025-26-budget-england',
    sourceType: 'budget-statistics', rightsStatus: 'licensed-for-reuse', sourceAccessCheckedAt: '2026-07-26',
    sourceNotes: 'Официальная статистика демонстрирует сверяемую структуру бюджета, доли и итоговые показатели.',
    adaptationPrinciple: 'Executive KPI-слайд, где инвестиция, эффект, ROI и срок окупаемости образуют единую логику решения.',
    originalDifference: 'Бизнес-кейс, цифры и визуализация созданы PIP; статистические таблицы и государственная айдентика не воспроизводятся.',
  },
]
